version: '3.8'

services:
  app:
    build: .
    ports:
      - "3001:3001"
      - "80:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATABASE_URL=${DATABASE_URL}
      - SESSION_SECRET=${SESSION_SECRET}
      - REPL_ID=${REPL_ID}
      - REPLIT_DOMAINS=207.180.239.163:3001,invexqr.com
      - ISSUER_URL=https://replit.com/oidc
      - SMTP_HOST=mail.infomaniak.com
      - SMTP_PORT=587
      - SMTP_SECURE=false
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - EMAIL_FROM=contact@invexqr.com
      - VITE_FIREBASE_API_KEY=${VITE_FIREBASE_API_KEY}
      - VITE_FIREBASE_PROJECT_ID=${VITE_FIREBASE_PROJECT_ID}
      - VITE_FIREBASE_APP_ID=${VITE_FIREBASE_APP_ID}
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - app_logs:/app/logs
    networks:
      - invexqr-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/public/stats"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-invexqr}
      - POSTGRES_USER=${POSTGRES_USER:-invexqr}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - invexqr-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-invexqr}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  app_logs:

networks:
  invexqr-network:
    driver: bridge