version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: invexqr-postgres
    environment:
      POSTGRES_DB: invexqr
      POSTGRES_USER: invexqr_user
      POSTGRES_PASSWORD: invexqr_secure_password_2024
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U invexqr_user -d invexqr"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: